<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'MyVendorPrefix\\voku\\' => array($vendorDir . '/voku/portable-ascii/src/voku'),
    'MyVendorPrefix\\Symfony\\Polyfill\\Php80\\' => array($vendorDir . '/symfony/polyfill-php80'),
    'MyVendorPrefix\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'MyVendorPrefix\\Symfony\\Polyfill\\Intl\\Normalizer\\' => array($vendorDir . '/symfony/polyfill-intl-normalizer'),
    'MyVendorPrefix\\Symfony\\Polyfill\\Intl\\Grapheme\\' => array($vendorDir . '/symfony/polyfill-intl-grapheme'),
    'MyVendorPrefix\\Symfony\\Polyfill\\Ctype\\' => array($vendorDir . '/symfony/polyfill-ctype'),
    'MyVendorPrefix\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'MyVendorPrefix\\Symfony\\Contracts\\Service\\' => array($vendorDir . '/symfony/service-contracts'),
    'MyVendorPrefix\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'MyVendorPrefix\\Symfony\\Component\\String\\' => array($vendorDir . '/symfony/string'),
    'MyVendorPrefix\\Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'MyVendorPrefix\\Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'MyVendorPrefix\\Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'MyVendorPrefix\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'MyVendorPrefix\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'MyVendorPrefix\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'MyVendorPrefix\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'MyVendorPrefix\\Phinx\\' => array($vendorDir . '/robmorgan/phinx/src/Phinx'),
    'MyVendorPrefix\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/conditionable', $vendorDir . '/illuminate/macroable', $vendorDir . '/illuminate/support'),
    'MyVendorPrefix\\Illuminate\\Database\\' => array($vendorDir . '/illuminate/database'),
    'MyVendorPrefix\\Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'MyVendorPrefix\\Illuminate\\Container\\' => array($vendorDir . '/illuminate/container'),
    'MyVendorPrefix\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib/Doctrine/Inflector'),
    'MyVendorPrefix\\Dbout\\WpOrm\\' => array($vendorDir . '/dbout/wp-orm/src'),
    'MyVendorPrefix\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'MyVendorPrefix\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'MyVendorPrefix\\Cake\\Utility\\' => array($vendorDir . '/cakephp/utility'),
    'MyVendorPrefix\\Cake\\Datasource\\' => array($vendorDir . '/cakephp/datasource'),
    'MyVendorPrefix\\Cake\\Database\\' => array($vendorDir . '/cakephp/database'),
    'MyVendorPrefix\\Cake\\Core\\' => array($vendorDir . '/cakephp/core'),
    'MyVendorPrefix\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
    'MyVendorPrefix\\Bamarni\\Composer\\Bin\\' => array($vendorDir . '/bamarni/composer-bin-plugin/src'),
    'MyPluginNamespace\\' => array($baseDir . '/src'),
);
